spring.application.name=poke-idle-3d
spring.datasource.url=${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=DB_POKEIDLE3D;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:SenhaForte123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
integrations.pokeapi.base-url=${POKEAPI_BASE_URL:https://pokeapi.co/api/v2}
